//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGoods
    {
        public tbGoods()
        {
            this.tbStars = new HashSet<tbStars>();
        }
    
        public string Goods_Idstr { get; set; }
        public string Goods_Namestr { get; set; }
        public string Goods_Descriptionstr { get; set; }
        public Nullable<double> Goods_Priceint { get; set; }
        public string Goos_Quality { get; set; }
        public Nullable<int> Goods_OldPriceint { get; set; }
        public Nullable<int> Goods_Starsint { get; set; }
        public string Goods_Imgstr { get; set; }
        public Nullable<int> Goods_Delflagint { get; set; }
        public Nullable<System.DateTime> Goods_Createdate { get; set; }
        public Nullable<int> Goods_UserIDint { get; set; }
        public Nullable<int> Goods_TypeIDint { get; set; }
    
        public virtual tbType tbType { get; set; }
        public virtual tbUser_Info tbUser_Info { get; set; }
        public virtual ICollection<tbStars> tbStars { get; set; }
    }
}
