//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbStars
    {
        public int IDint { get; set; }
        public Nullable<int> Stars_UserIDint { get; set; }
        public string Stars_GoodsIDstr { get; set; }
        public Nullable<System.DateTime> Stars_Datedate { get; set; }
    
        public virtual tbGoods tbGoods { get; set; }
        public virtual tbUser_Info tbUser_Info { get; set; }
    }
}
