//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbType
    {
        public tbType()
        {
            this.tbGoods = new HashSet<tbGoods>();
        }
    
        public int IDint { get; set; }
        public string Type_Namestr { get; set; }
        public Nullable<int> Type_Delfalgint { get; set; }
        public string Type_IDstr { get; set; }
    
        public virtual ICollection<tbGoods> tbGoods { get; set; }
        public virtual tbType tbType1 { get; set; }
        public virtual tbType tbType2 { get; set; }
    }
}
