//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser_Info
    {
        public tbUser_Info()
        {
            this.tbCommodity = new HashSet<tbCommodity>();
        }
    
        public byte User_Idint { get; set; }
        public string User_Emailstr { get; set; }
        public string User_Pwdstr { get; set; }
    
        public virtual ICollection<tbCommodity> tbCommodity { get; set; }
    }
}
