//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VI_USER_INFO
    {
        public int User_IDint { get; set; }
        public string User_Emailstr { get; set; }
        public string User_Biostr { get; set; }
        public string User_Nicknamestr { get; set; }
        public string User_Genderchar { get; set; }
        public Nullable<System.DateTime> User_Birthdaydate { get; set; }
        public string User_Phonestr { get; set; }
        public string User_Iconstr { get; set; }
        public string User_Adress { get; set; }
        public string User_Hobaystr { get; set; }
        public Nullable<System.DateTime> User_CreateTimedate { get; set; }
        public Nullable<System.DateTime> User_LastLoginTinedate { get; set; }
        public string User_Namestr { get; set; }
        public string User_Realnamestr { get; set; }
    }
}
