//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBuy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCommodity
    {
        public string Commodity_Idstr { get; set; }
        public string Commodity_Namestr { get; set; }
        public string Commodity_Descriptionstr { get; set; }
        public Nullable<int> Commodity_Priceint { get; set; }
        public string Commodity_Quality { get; set; }
        public Nullable<int> Commodity_OldPriceint { get; set; }
        public Nullable<int> Commodity_Starint { get; set; }
        public Nullable<byte> Commodity_Userint { get; set; }
    
        public virtual tbUser_Info tbUser_Info { get; set; }
    }
}
